version: '3.9'

services:
  betting_app:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on: [database]
    environment:
      DB_PASSWORD: mysecretpassword
      NODE_ENV: development
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
